name: Deploy Backend API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.VM_USER }}/app

            # Copy app.py and requirements.txt
            cat > /home/${{ secrets.VM_USER }}/app/app.py <<'EOF'
$(cat app.py)
EOF

            cat > /home/${{ secrets.VM_USER }}/app/requirements.txt <<'EOF'
$(cat requirements.txt)
EOF

            cd /home/${{ secrets.VM_USER }}/app

            # Install dependencies
            pip install -r requirements.txt

            # Stop any old process and start new one in background
            sudo pkill -f "python3 app.py" || true
            nohup sudo python3 app.py > app.log 2>&1 &
